CREATE TABLE IF NOT EXISTS content_revisions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  entity_type ENUM('subject', 'college', 'branch_profile') NOT NULL,
  entity_key VARCHAR(255) NOT NULL,
  revision_number INT UNSIGNED NOT NULL,
  content_json JSON NOT NULL,
  source_status VARCHAR(64) NOT NULL,
  proposal_id BIGINT UNSIGNED NULL,
  export_id BIGINT UNSIGNED NULL,
  draft_apply_id BIGINT UNSIGNED NULL,
  parent_revision_id BIGINT UNSIGNED NULL,
  created_by VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_content_revisions_entity_revision (entity_type, entity_key, revision_number),
  KEY idx_content_revisions_entity_latest (entity_type, entity_key, revision_number),
  KEY idx_content_revisions_proposal (proposal_id),
  KEY idx_content_revisions_export (export_id),
  KEY idx_content_revisions_draft_apply (draft_apply_id),
  KEY idx_content_revisions_parent (parent_revision_id),
  CONSTRAINT fk_content_revisions_proposal FOREIGN KEY (proposal_id) REFERENCES content_proposals(id) ON DELETE SET NULL,
  CONSTRAINT fk_content_revisions_export FOREIGN KEY (export_id) REFERENCES proposal_exports(id) ON DELETE SET NULL,
  CONSTRAINT fk_content_revisions_draft_apply FOREIGN KEY (draft_apply_id) REFERENCES proposal_draft_applies(id) ON DELETE SET NULL,
  CONSTRAINT fk_content_revisions_parent FOREIGN KEY (parent_revision_id) REFERENCES content_revisions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
